## 1 Python错误，异常捕获和处理

错误可以分为两类：语法（解析）错误和逻辑（算法）错误。

异常是一个事件，该事件在程序执行过程中发生，影响程序的正常执行。一般情况下，Python无法正常处理程序时就会发生一个异常。

### 1.1 异常的处理
#### 1.1.1 try-except
它能够将可能出错的代码进行处理，处理后报错的红色字体将会转换成简短的、正常的字体，用法如下：
```python
try:
    有可能出现异常的代码
except  异常类型 as 变量
	处理后的代码
	
这里的try-except并不影响代码的运行，如果你的代码没有报错，就算是写了tyr-except，它也只会执行try那行代码。如果那行代码没有错误，那就不会执行except里面的代码。
```

#### 1.1.2 try-except-except
可用于判断多种可能报错的情况，类似多elif
用法如下：

```python
try:
    1 / 0
    print(a)
except NameError as s:  # 第一种写法，用as+变量
    print(s)
except ZeroDivisionError:  # 第二种写法，自定义输出内容
    print("除数不能为0")  # 自定义输出的内容
```
try-except的写法很灵活，我们同样可以用元组把可能报错的异常类型囊括进去，避免写多行except.

#### 1.1.3 try-except-else
如果没有异常，则执行else里面的代码

#### 1.1.4 try-except-finally
不管代码是否有异常，最后都会执行finally里面的代码

#### 1.1.5 顶层类Exception
except后面其实可以不加错误类型，因为系统会默认认为后面的错误是类型是Exception，这是1个顶层类，包含了所有的出错类型。

#### 1.1.6 小结

```python
try:    
    正常的操作    # 可能出现异常的代码块
except [异常类型]：    
    发生异常，执行这块代码      # 如果在try部份引发了'异常类型'异常
except [异常类型，数据]:    
    发生异常，执行这块代码      # 如果引发了'异常类型'异常，获得附加数据
except [异常类型]:    
    发生异常，执行这块代码
else:    
    如果没有异常执行这块代码
finally:    
    无论是否发生异常都将执行最后的代码
```

### 1.2 自定义异常

有没有发现，前面我们去做基本的异常捕获时，每次可能出错的地方就得写一个try-except，如果有多个地方可能会出错呢？是否我们需要写多个try-except？又或者理论上代码可以运行，但我想定一下规矩，凡是不符合我规矩的行为，我都让它出现异常，比如密码长度超出我规定的长度，我想让程序出现异常。

**自定义异常可用于引发一个异常（抛出一个异常），由关键字raise引发。**

举例：模拟用户输入密码的情景，用户输入的密码不能低于6位数，自定义一个异常，用于检测用户输入的密码是否符合规定，不符合则引发异常，提示当前输入的密码长度和最小密码长度不能低于6位数。
```python
class MyError(Exception):  # 异常捕获的类
    def __init__(self, length, min_len):  # length为用户输入的密码长度，min_len为规定的最小长度
        self.length = length
        self.min_len = min_len

    # 设置抛出异常的描述信息
    def __str__(self):
        return "你输入的长度是%s,不能少于%s" % (self.length, self.min_len)


def main():
    try:
        con = input("请输入密码：")  # 获取用户输入的密码
        l = len(con)  # 获取用户输入的密码长度
        if l < 6:
            raise MyError(l, 6)  # 长度低于设定的6位数则引发异常
    except Exception as ss:  # 有错误则提示
        print(ss)
    else:
        print("您的密码输入完毕")  # 没有错误则执行

main()
```